// Generated by CoffeeScript 1.7.1
(function() {
  var Mask;

  Mask = require('../mask.coffee');

  module.exports = {
    parseMaskData: function() {
      return this.mask = new Mask(this.file).parse();
    }
  };

}).call(this);
