// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    Greyscale: require('./image_modes/greyscale.coffee'),
    RGB: require('./image_modes/rgb.coffee'),
    CMYK: require('./image_modes/cmyk.coffee')
  };

}).call(this);
